### ISSUE TITLE
How to built it?

### ISSUE THREAD

**Issue by mabra** [edubart/bwrapbox#1]
This looks appropriate and bring, what other packages are missing.
How can I build/use it (not a devolper)?

**Comment by edubart** [comment]
Just clone and type `make bwrapbox`, as long you have `gcc` compiler and Linux headers it should work.

**Comment by mabra** [comment]
> Just clone and type `make bwrapbox`, as long you have `gcc` compiler and Linux headers it should work.

Thanks!
